/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQuerySyncDetailsEndPointApi.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   syncDetailsEndPointApi/v1
// Description:
//   This is an API
// Classes:
//   GTLQuerySyncDetailsEndPointApi (2 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@interface GTLQuerySyncDetailsEndPointApi : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, copy) NSString *email;
@property (nonatomic, assign) long long syncFromServerTime;
@property (nonatomic, assign) long long syncToServerTime;

#pragma mark - Service level methods
// These create a GTLQuerySyncDetailsEndPointApi object.

// Method: syncDetailsEndPointApi.getSyncDetails
//  Authorization scope(s):
//   kGTLAuthScopeSyncDetailsEndPointApiUserinfoEmail
// Fetches a GTLSyncDetailsEndPointApiSyncDetailsBean.
+ (instancetype)queryForGetSyncDetailsWithEmail:(NSString *)email;

// Method: syncDetailsEndPointApi.updateSyncTime
//  Authorization scope(s):
//   kGTLAuthScopeSyncDetailsEndPointApiUserinfoEmail
// Fetches a GTLSyncDetailsEndPointApiSyncDetailsBean.
+ (instancetype)queryForUpdateSyncTimeWithEmail:(NSString *)email
                             syncFromServerTime:(long long)syncFromServerTime
                               syncToServerTime:(long long)syncToServerTime;

@end
