/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryUserEndPointApi.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userEndPointApi/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryUserEndPointApi (2 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@interface GTLQueryUserEndPointApi : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, copy) NSString *displayName;
@property (nonatomic, copy) NSString *email;

#pragma mark - Service level methods
// These create a GTLQueryUserEndPointApi object.

// Method: userEndPointApi.createUser
//  Authorization scope(s):
//   kGTLAuthScopeUserEndPointApiUserinfoEmail
// Fetches a GTLUserEndPointApiUserBean.
+ (instancetype)queryForCreateUserWithDisplayName:(NSString *)displayName
                                            email:(NSString *)email;

// Method: userEndPointApi.getUser
//  Authorization scope(s):
//   kGTLAuthScopeUserEndPointApiUserinfoEmail
// Fetches a GTLUserEndPointApiUserBean.
+ (instancetype)queryForGetUserWithEmail:(NSString *)email;

@end
