/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQuerySongCategoryEndPointApi.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   songCategoryEndPointApi/v1
// Description:
//   This is an API
// Classes:
//   GTLQuerySongCategoryEndPointApi (2 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@interface GTLQuerySongCategoryEndPointApi : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, assign) long long after;
@property (nonatomic, assign) long long level;
@property (nonatomic, copy) NSString *name;

#pragma mark - Service level methods
// These create a GTLQuerySongCategoryEndPointApi object.

// Method: songCategoryEndPointApi.createCategory
//  Authorization scope(s):
//   kGTLAuthScopeSongCategoryEndPointApiUserinfoEmail
// Fetches a GTLSongCategoryEndPointApiSongCategoryBean.
+ (instancetype)queryForCreateCategoryWithName:(NSString *)name
                                         level:(long long)level;

// Method: songCategoryEndPointApi.getCategories
//  Authorization scope(s):
//   kGTLAuthScopeSongCategoryEndPointApiUserinfoEmail
// Fetches a GTLSongCategoryEndPointApiCollectionResponseSongCategoryBean.
+ (instancetype)queryForGetCategoriesWithAfter:(long long)after;

@end
