/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQuerySyncDetailsEndPointApi.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   syncDetailsEndPointApi/v1
// Description:
//   This is an API
// Classes:
//   GTLQuerySyncDetailsEndPointApi (2 custom class methods, 4 custom properties)

#import "GTLQuerySyncDetailsEndPointApi.h"

#import "GTLSyncDetailsEndPointApiSyncDetailsBean.h"

@implementation GTLQuerySyncDetailsEndPointApi

@dynamic email, fields, syncFromServerTime, syncToServerTime;

#pragma mark - Service level methods
// These create a GTLQuerySyncDetailsEndPointApi object.

+ (instancetype)queryForGetSyncDetailsWithEmail:(NSString *)email {
  NSString *methodName = @"syncDetailsEndPointApi.getSyncDetails";
  GTLQuerySyncDetailsEndPointApi *query = [self queryWithMethodName:methodName];
  query.email = email;
  query.expectedObjectClass = [GTLSyncDetailsEndPointApiSyncDetailsBean class];
  return query;
}

+ (instancetype)queryForUpdateSyncTimeWithEmail:(NSString *)email
                             syncFromServerTime:(long long)syncFromServerTime
                               syncToServerTime:(long long)syncToServerTime {
  NSString *methodName = @"syncDetailsEndPointApi.updateSyncTime";
  GTLQuerySyncDetailsEndPointApi *query = [self queryWithMethodName:methodName];
  query.email = email;
  query.syncFromServerTime = syncFromServerTime;
  query.syncToServerTime = syncToServerTime;
  query.expectedObjectClass = [GTLSyncDetailsEndPointApiSyncDetailsBean class];
  return query;
}

@end
