/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQuerySongCategoryEndPointApi.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   songCategoryEndPointApi/v1
// Description:
//   This is an API
// Classes:
//   GTLQuerySongCategoryEndPointApi (2 custom class methods, 4 custom properties)

#import "GTLQuerySongCategoryEndPointApi.h"

#import "GTLSongCategoryEndPointApiCollectionResponseSongCategoryBean.h"
#import "GTLSongCategoryEndPointApiSongCategoryBean.h"

@implementation GTLQuerySongCategoryEndPointApi

@dynamic after, fields, level, name;

#pragma mark - Service level methods
// These create a GTLQuerySongCategoryEndPointApi object.

+ (instancetype)queryForCreateCategoryWithName:(NSString *)name
                                         level:(long long)level {
  NSString *methodName = @"songCategoryEndPointApi.createCategory";
  GTLQuerySongCategoryEndPointApi *query = [self queryWithMethodName:methodName];
  query.name = name;
  query.level = level;
  query.expectedObjectClass = [GTLSongCategoryEndPointApiSongCategoryBean class];
  return query;
}

+ (instancetype)queryForGetCategoriesWithAfter:(long long)after {
  NSString *methodName = @"songCategoryEndPointApi.getCategories";
  GTLQuerySongCategoryEndPointApi *query = [self queryWithMethodName:methodName];
  query.after = after;
  query.expectedObjectClass = [GTLSongCategoryEndPointApiCollectionResponseSongCategoryBean class];
  return query;
}

@end
