/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLSyncDetailsEndPointApiSyncDetailsBean.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   syncDetailsEndPointApi/v1
// Description:
//   This is an API
// Classes:
//   GTLSyncDetailsEndPointApiSyncDetailsBean (0 custom class methods, 4 custom properties)

#import "GTLSyncDetailsEndPointApiSyncDetailsBean.h"

// ----------------------------------------------------------------------------
//
//   GTLSyncDetailsEndPointApiSyncDetailsBean
//

@implementation GTLSyncDetailsEndPointApiSyncDetailsBean
@dynamic identifier, syncFromServerTime, syncToServerTime, userEmail;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

@end
