/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLSyncDetailsEndPointApi.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   syncDetailsEndPointApi/v1
// Description:
//   This is an API

#import "GTLSyncDetailsEndPointApiConstants.h"

#import "GTLSyncDetailsEndPointApiSyncDetailsBean.h"

#import "GTLQuerySyncDetailsEndPointApi.h"
#import "GTLServiceSyncDetailsEndPointApi.h"
