/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLSongDetailsEndPointApi.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   songDetailsEndPointApi/v1
// Description:
//   This is an API

#import "GTLSongDetailsEndPointApiConstants.h"

#import "GTLSongDetailsEndPointApiCollectionResponseSongDetailsBean.h"
#import "GTLSongDetailsEndPointApiSongDetailsBean.h"

#import "GTLQuerySongDetailsEndPointApi.h"
#import "GTLServiceSongDetailsEndPointApi.h"
