/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLSongCategoryEndPointApiSongCategoryBean.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   songCategoryEndPointApi/v1
// Description:
//   This is an API
// Classes:
//   GTLSongCategoryEndPointApiSongCategoryBean (0 custom class methods, 5 custom properties)

#import "GTLSongCategoryEndPointApiSongCategoryBean.h"

// ----------------------------------------------------------------------------
//
//   GTLSongCategoryEndPointApiSongCategoryBean
//

@implementation GTLSongCategoryEndPointApiSongCategoryBean
@dynamic creationDate, identifier, level, name, updatedDate;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

@end
