/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLSongDetailsEndPointApiSongDetailsBean.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   songDetailsEndPointApi/v1
// Description:
//   This is an API
// Classes:
//   GTLSongDetailsEndPointApiSongDetailsBean (0 custom class methods, 12 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLSongDetailsEndPointApiSongDetailsBean
//

@interface GTLSongDetailsEndPointApiSongDetailsBean : GTLObject
@property (nonatomic, copy) NSString *aarohana;
@property (nonatomic, copy) NSString *avarohana;
@property (nonatomic, copy) NSString *categoryName;
@property (nonatomic, retain) GTLDateTime *creationDate;
@property (nonatomic, copy) NSString *details;
@property (nonatomic, retain) NSNumber *duration;  // doubleValue

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, retain) NSNumber *identifier;  // longLongValue

@property (nonatomic, copy) NSString *pictureUrl;
@property (nonatomic, copy) NSString *ragam;
@property (nonatomic, copy) NSString *title;
@property (nonatomic, retain) GTLDateTime *updatedDate;
@property (nonatomic, copy) NSString *videoUrl;
@end
