/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLSongCategoryEndPointApi.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   songCategoryEndPointApi/v1
// Description:
//   This is an API

#import "GTLSongCategoryEndPointApiConstants.h"

#import "GTLSongCategoryEndPointApiCollectionResponseSongCategoryBean.h"
#import "GTLSongCategoryEndPointApiSongCategoryBean.h"

#import "GTLQuerySongCategoryEndPointApi.h"
#import "GTLServiceSongCategoryEndPointApi.h"
