/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLSyncDetailsEndPointApi_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   syncDetailsEndPointApi/v1
// Description:
//   This is an API

#import "GTLSyncDetailsEndPointApiConstants.m"

#import "GTLSyncDetailsEndPointApiSyncDetailsBean.m"

#import "GTLQuerySyncDetailsEndPointApi.m"
#import "GTLServiceSyncDetailsEndPointApi.m"
