/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLSyncDetailsEndPointApiConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   syncDetailsEndPointApi/v1
// Description:
//   This is an API

#import "GTLSyncDetailsEndPointApiConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeSyncDetailsEndPointApiUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
