/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLSongCategoryEndPointApiConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   songCategoryEndPointApi/v1
// Description:
//   This is an API

#import "GTLSongCategoryEndPointApiConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeSongCategoryEndPointApiUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
