/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLSongDetailsEndPointApiSongDetailsBean.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   songDetailsEndPointApi/v1
// Description:
//   This is an API
// Classes:
//   GTLSongDetailsEndPointApiSongDetailsBean (0 custom class methods, 12 custom properties)

#import "GTLSongDetailsEndPointApiSongDetailsBean.h"

// ----------------------------------------------------------------------------
//
//   GTLSongDetailsEndPointApiSongDetailsBean
//

@implementation GTLSongDetailsEndPointApiSongDetailsBean
@dynamic aarohana, avarohana, categoryName, creationDate, details, duration,
         identifier, pictureUrl, ragam, title, updatedDate, videoUrl;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

@end
