/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLSongDetailsEndPointApiCollectionResponseSongDetailsBean.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   songDetailsEndPointApi/v1
// Description:
//   This is an API
// Classes:
//   GTLSongDetailsEndPointApiCollectionResponseSongDetailsBean (0 custom class methods, 2 custom properties)

#import "GTLSongDetailsEndPointApiCollectionResponseSongDetailsBean.h"

#import "GTLSongDetailsEndPointApiSongDetailsBean.h"

// ----------------------------------------------------------------------------
//
//   GTLSongDetailsEndPointApiCollectionResponseSongDetailsBean
//

@implementation GTLSongDetailsEndPointApiCollectionResponseSongDetailsBean
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLSongDetailsEndPointApiSongDetailsBean class]
  };
  return map;
}

@end
