/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLSongDetailsEndPointApiConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   songDetailsEndPointApi/v1
// Description:
//   This is an API

#import "GTLSongDetailsEndPointApiConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeSongDetailsEndPointApiUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
