/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLSyncDetailsEndPointApiSyncDetailsBean.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   syncDetailsEndPointApi/v1
// Description:
//   This is an API
// Classes:
//   GTLSyncDetailsEndPointApiSyncDetailsBean (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLSyncDetailsEndPointApiSyncDetailsBean
//

@interface GTLSyncDetailsEndPointApiSyncDetailsBean : GTLObject

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, retain) NSNumber *identifier;  // longLongValue

@property (nonatomic, retain) GTLDateTime *syncFromServerTime;
@property (nonatomic, retain) GTLDateTime *syncToServerTime;
@property (nonatomic, copy) NSString *userEmail;
@end
