/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLSongCategoryEndPointApi_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   songCategoryEndPointApi/v1
// Description:
//   This is an API

#import "GTLSongCategoryEndPointApiConstants.m"

#import "GTLSongCategoryEndPointApiCollectionResponseSongCategoryBean.m"
#import "GTLSongCategoryEndPointApiSongCategoryBean.m"

#import "GTLQuerySongCategoryEndPointApi.m"
#import "GTLServiceSongCategoryEndPointApi.m"
