/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUserEndPointApiConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userEndPointApi/v1
// Description:
//   This is an API

#import "GTLUserEndPointApiConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeUserEndPointApiUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
